# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- name: Create reaper group
  become: true
  group:
    name: reaper
    system: yes
- name: Create reaper user
  become: true
  user:
    name: reaper
    group: reaper
    createhome: no
    system: yes
    
