# (c) 2017 DataNexus Inc.  All Rights Reserved

- name: Download cassandra-reaper to /tmp
  become: true
  get_url:
    url: "{{reaper_url}}"
    dest: /tmp
    mode: 0644
    validate_certs: no
  environment: "{{environment_vars}}"
- name: Create "{{reaper_dir}}"
  become: true
  file:
    path: "{{reaper_dir}}"
    state: directory
    owner: reaper
    group: reaper
- name: Unpack reaper distribution into "{{reaper_dir}}"
  become: true
  unarchive:
    copy: no
    src: "/tmp/cassandra-reaper-v{{reaper_version}}-release.tar.gz"
    dest: "{{reaper_dir}}"
    extra_opts: [ "--strip-components=1" ]
    owner: reaper
    group: reaper
- name: Create reaper configuration
  become: true
  template:
    src: "../templates/reaper.yaml"
    dest: "{{reaper_dir}}/reaper.yaml"
    mode: 0644
- name: Create start script
  become: true
  template:
    src: "../templates/start.sh"
    dest: "{{reaper_dir}}/start.sh"
    mode: 0744
    owner: reaper
    group: reaper
- name: Create stop script
  become: true
  template:
    src: "../templates/stop.sh"
    dest: "{{reaper_dir}}/stop.sh"
    mode: 0744
    owner: reaper
    group: reaper


